/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wrcxljunhiwmrilxisyd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyY3hsanVuaGl3bXJpbHhpc3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MDMxMTUsImV4cCI6MjA4NzM3OTExNX0.SUlEGPEsYfxC5_VWpgeBstAcyyE-hN29HfQRTckz-5g"